---
title: "Problema 1 - Checkpoint 4"
author: "Leticia Wanderley"
date: "23 de maio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("tidyr")
library("ggplot2")
library("readr")
```

## Problema 1 - Checkpoint 4

```{r series, include=FALSE}
dados = read_csv("series_from_imdb.csv")
names = unique(dados$series_name)
```

### Existe algum ponto de virada entre as temporadas de uma série depois do qual as notas começam a diminuir/aumentar?
```{r}
series_median <- 
  dados %>%
  group_by(series_name, season) %>%
  summarise(mediana=median(UserRating))

series_median %>%
  ggplot(aes(x=reorder(season, season, FUN=median), y=mediana)) + theme_bw() +
  geom_boxplot() 

seasons_median <-
  series_median %>%
  group_by(season) %>%
  summarise(mediana=median(mediana))

seasons_median %>%
  ggplot(aes(x=season, y=mediana)) + theme_bw() +
  geom_line() 
```

### O episódio piloto tem mais notas mínimas que o episódio final da série?
```{r loadPart2, include=FALSE}
series <- 
  dados %>%
    group_by(series_name) %>%
    filter(series_ep %in% c(min(series_ep), max(series_ep))) %>%
    arrange(series_name) %>%
    mutate(diff = r1 - lag(r1, default=first(r1))) %>%
    filter(diff != 0.0)
# diferença entre o número de notas 1 do último episódio e o número de notas 1 do primeiro
series %>%
  ggplot(mapping = aes(x = series_name, y=diff)) +
  geom_point()
```
